[build]
    base = "frontend"
    command = "react-scripts build"
    publish="frontend/build"

[context.production]
    environment = { REACT_APP_BACKEND_URL='https://engineeringblogs-backend.herokuapp.com//feeds' }